CREATE DATABASE PYPG3;

USE PYPG3;

CREATE TABLE ROl(
	PK_IDROL INT AUTO_INCREMENT,
    DescripcionRol VARCHAR(30) NOT NULL,
    Activo BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_IDROL PRIMARY KEY(PK_IDROL)
) ENGINE=INNODB;

INSERT INTO ROl(DescripcionRol)
VALUES ('Proveedor'), ('Cliente');

CREATE TABLE Usuario(
	NombreUsuario VARCHAR(100) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
	FechaNacimiento DATE NOT NULL,
    PK_Correo VARCHAR(100) NOT NULL,
	Contrasena VARBINARY(32) NOT NULL,
	Salt VARBINARY(32) NOT NULL,
	Activo BIT NOT NULL DEFAULT 1,
    IDRol INT NOT NULL,
	CONSTRAINT FK_ROL_Usuario FOREIGN KEY (IDRol) REFERENCES ROL(PK_IDROL) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT PK_Usuario PRIMARY KEY(PK_Correo),
    UNIQUE(NombreUsuario)
) ENGINE=INNODB;



CREATE TABLE Cliente(
	PK_IDCorreo VARCHAR(100) NOT NULL,
    Activo BIT NOT NULL DEFAULT 1,	
	PRIMARY KEY(PK_IDCorreo),
    CONSTRAINT PK_Cliente FOREIGN KEY (PK_IDCorreo) REFERENCES Usuario(PK_Correo) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE=INNODB;

#Tablas para los incidentes 
CREATE TABLE Proveedor(
	PK_IDCorreo VARCHAR(100) NOT NULL, 
    Activo BIT NOT NULL DEFAULT 1,
    PRIMARY KEY(PK_IDCorreo),
    CONSTRAINT PK_Proveedor FOREIGN KEY (PK_IDCorreo) REFERENCES Usuario(PK_Correo) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE=INNODB;

CREATE TABLE TipoSoftware(
	PK_IDTipoSoftware INT AUTO_INCREMENT NOT NULL,
    DescripcionTipoSoftware VARCHAR(100) NOT NULL,
    Activo BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_TipoSoftware PRIMARY KEY(PK_IDTipoSoftware)
);

CREATE TABLE Software(
	PK_IDSoftware INT AUTO_INCREMENT,
    NombreSoftware VARCHAR(45) NOT NULL,
    DescripcionSoftware VARCHAR(45) NOT NULL,
    Activo BIT NOT NULL DEFAULT 1,
    TipoSoftware INT NOT NULL,
    CONSTRAINT PK_Software PRIMARY KEY(PK_IDSoftware),
    CONSTRAINT FK_TipoSoftware_Software FOREIGN KEY (TipoSoftware) REFERENCES TipoSoftware(PK_IDTipoSoftware) ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE=INNODB;

CREATE TABLE TipoIncidente(
	PK_IDTipoIncidente INT AUTO_INCREMENT,
    DescripcionTipoIncidente VARCHAR(45),
    Activo BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_TipoIncidente PRIMARY KEY(PK_IDTipoIncidente)
) ENGINE=INNODB;

CREATE TABLE EstadoIncidente(
	PK_IDEstadoIncidente INT AUTO_INCREMENT,
    DescripcionEstadoIncidente VARCHAR(45) NOT NULL,
    Activo BIT NOT NULL DEFAULT 1,
	CONSTRAINT PK_EstadoIncidente PRIMARY KEY (PK_IDEstadoIncidente)
) ENGINE=INNODB;

CREATE TABLE Incidente(
	PK_IDIncidente INT AUTO_INCREMENT,
    NombreIncidente VARCHAR(45) NOT NULL,
    DescripcionIncidente VARCHAR(500) NOT NULL,
    EstadoIncidente INT NOT NULL,
    TipoIncidente INT NOT NULL,
    Cliente VARCHAR(100) NOT NULL,
    Proveedor VARCHAR(100) NOT NULL,
    CONSTRAINT FK_TipoIncidente_Incidente FOREIGN KEY (TipoIncidente) REFERENCES TipoIncidente(PK_IDTipoIncidente)  ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Cliente_Incidente FOREIGN KEY (Cliente) REFERENCES Cliente(PK_IDCorreo) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Proveedor_Incidente FOREIGN KEY (Proveedor) REFERENCES Proveedor(PK_IDCorreo) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_EstadoIncidente_Incidente FOREIGN KEY (EstadoIncidente) REFERENCES EstadoIncidente(PK_IDEstadoIncidente) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT PK_Incidente PRIMARY KEY (PK_IDIncidente),
	Activo BIT NOT NULL DEFAULT 1
) ENGINE=INNODB;


CREATE TABLE Comentarios(
	PK_IDComentarios INT AUTO_INCREMENT,
    DescripcionComentario VARCHAR(300) NOT NULL,
    Incidente INT NOT NULL,
    Usuario VARCHAR(100),
    Activo BIT NOT NULL DEFAULT 1,
    CONSTRAINT FK_Incidente_Comentarios FOREIGN KEY (Incidente) REFERENCES Incidente(PK_IDIncidente),
    CONSTRAINT FK_Usuario_Comentarios FOREIGN KEY (Usuario) REFERENCES Usuario(PK_Correo),
    CONSTRAINT PK_IDComentarios PRIMARY KEY(PK_IDComentarios)
    
) ENGINE=INNODB;

CREATE TABLE Documentos(
	PK_IDDocumentos INT AUTO_INCREMENT,
    DescripcionDocumentos VARCHAR(45) NOT NULL,
    Documento MEDIUMBLOB NOT NULL,
    Incidente INT NOT NULL,
    Activo BIT NOT NULL DEFAULT 1,
    CONSTRAINT FK_Incidente_Documentos FOREIGN KEY (Incidente) REFERENCES Incidente(PK_IDIncidente) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT PK_Documentos PRIMARY KEY(PK_IDDocumentos)
) ENGINE=INNODB;

